# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Va_hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('hours', models.TimeField()),
                ('work_type', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
                ('customer_oportunity', models.CharField(max_length=200)),
            ],
        ),
    ]
