# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_hora', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='va_hora',
            old_name='nome',
            new_name='name',
        ),
    ]
