# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_hora', '0003_va_hora_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='va_hora',
            old_name='year_in_school',
            new_name='teste',
        ),
    ]
